os: linux
dist: trusty
language: python
python: 3.6

install:
  - pip3 install pipenv
  - pipenv install

script: pipenv run python bin/build.py

after_success:
  - rm .gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
