os: linux
dist: bionic
language: python
python: 3.8

install:
  - pip install -r requirements.txt

script:
  - python3 bin/build.py

after_success:
  - rm -rf .* bin/ LICENSE CODE_OF_CONDUCT.md README.md requirements.txt

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
