os: linux
distro: trusty
langauge: python
python: 3.6

install: pip3 install -r requirements.txt

script: python3 bin/build.py

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
